#!/usr/bin/env python3
"""v5 seed data generator runner.

Calls each stage module in dependency order (FK-respecting) and writes
seed.sql at the parent `backend/seed/` directory. Determinism: stage
modules use only fixed seeds and ordered iteration; rerunning produces
byte-identical output.

Invocation (from `backend/seed/`):
    python -m generate_seed_v5.runner
"""
import importlib
import os
import sys

# FK-respecting stage order. See plan doc § "Stage Ordering".
MODULES = [
    "s01_taxonomy",
    "s02_grouping_entities",
    "s03_legal_entities_locs",
    "s04_roles_rates",
    "s05_people",
    "s06_chargeable_entities",
    "s07_assignments",
    "s08_distribution",
    "s09_btc",
    "s10_um_matrix",
    "s11_tech_navigator",
    "s12_pipeline",
    "s13_financials",
    "s14_allocations",
    "s15_change_requests",
    "s16_workflow",
    "s17_milestones",
    "s18_progress",
    "s19_scenarios",
    "s20_system",
]


def main() -> None:
    parts: list[str] = []
    parts.append("-- =============================================================================")
    parts.append("-- VIPER Demo App — Seed Data (v5)")
    parts.append("-- Generated by backend/seed/generate_seed_v5/runner.py")
    parts.append("-- Demo date: April 2026")
    parts.append("-- Polymorphic ChargeableEntity model + Cluster F charging stack [F-DG-01..03]")
    parts.append("-- =============================================================================")
    parts.append("")

    for mod_name in MODULES:
        print(f"  Generating {mod_name}...", file=sys.stderr)
        mod = importlib.import_module(f"generate_seed_v5.{mod_name}")
        sql = mod.generate()
        parts.append(sql)
        parts.append("")

    output = "\n".join(parts)

    seed_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "seed.sql")
    with open(seed_path, "w") as f:
        f.write(output)

    line_count = output.count("\n") + 1
    print(f"\n  Done! Wrote {line_count} lines to {seed_path}", file=sys.stderr)

    # --- Entity roster banner (Phase 1 sanity check; read by Phase 2 teams).
    try:
        from generate_seed_v5.config.entities import ROSTER_BANNER_LINES
    except Exception:
        ROSTER_BANNER_LINES = []
    if ROSTER_BANNER_LINES:
        print("", file=sys.stderr)
        print("  -------------------------------------------", file=sys.stderr)
        print("  FROZEN ChargeableEntity roster [F-DG-01..03]", file=sys.stderr)
        print("  -------------------------------------------", file=sys.stderr)
        for line in ROSTER_BANNER_LINES:
            print(line, file=sys.stderr)


if __name__ == "__main__":
    main()
