"""baseline schema

Revision ID: d65d374b78c5
Revises: 
Create Date: 2026-06-08 10:48:45.405439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65d374b78c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competence_centers',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('iso_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso_code')
    )
    op.create_table('external_cost_types',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grouping_entity_types',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grouping_hierarchies',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active_hierarchy', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpi_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('display_format', sa.String(length=20), nullable=False),
    sa.Column('target_value', sa.String(length=100), nullable=True),
    sa.Column('is_built_in', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestone_types',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('default_color', sa.String(length=20), nullable=False),
    sa.Column('suggested_ordering', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planning_parameters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_value', sa.String(length=100), nullable=False),
    sa.Column('default_value', sa.String(length=100), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('param_group', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('regions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('role_permission_grants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_types',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('report_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('charging_locations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('region_id', sa.String(length=50), nullable=True),
    sa.Column('country_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cost_centers',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location_id', sa.String(length=50), nullable=False),
    sa.Column('competence_center_id', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competence_center_id'], ['competence_centers.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grouping_entities',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('entity_type_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_entity_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_type_id'], ['grouping_entity_types.id'], ),
    sa.ForeignKeyConstraint(['parent_entity_id'], ['grouping_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grouping_hierarchy_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hierarchy_id', sa.String(length=50), nullable=False),
    sa.Column('level_order', sa.Integer(), nullable=False),
    sa.Column('entity_type_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['entity_type_id'], ['grouping_entity_types.id'], ),
    sa.ForeignKeyConstraint(['hierarchy_id'], ['grouping_hierarchies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_type_id', sa.String(length=50), nullable=False),
    sa.Column('competence_center_id', sa.String(length=50), nullable=False),
    sa.Column('location_id', sa.String(length=50), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('effective_date', sa.String(length=10), nullable=False),
    sa.Column('previous_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('previous_effective_date', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competence_center_id'], ['competence_centers.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['role_type_id'], ['role_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_report_shares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('shared_with', sa.String(length=50), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['saved_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('step_type', sa.String(length=20), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('skippable', sa.Boolean(), nullable=False),
    sa.Column('assigned_role', sa.String(length=40), nullable=True),
    sa.Column('data_gates_json', sa.Text(), nullable=True),
    sa.Column('notifications_json', sa.Text(), nullable=True),
    sa.Column('time_constraint_days', sa.Integer(), nullable=True),
    sa.Column('escalation_action', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_entities',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('charging_location_id', sa.String(length=50), nullable=True),
    sa.Column('country_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['charging_location_id'], ['charging_locations.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('people',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role_type_id', sa.String(length=50), nullable=False),
    sa.Column('cost_center_id', sa.String(length=50), nullable=True),
    sa.Column('competence_center_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competence_center_id'], ['competence_centers.id'], ),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['role_type_id'], ['role_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_step_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('action_order', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_person_id', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('entity_name', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('field_changed', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.String(length=500), nullable=True),
    sa.Column('new_value', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=40), server_default='master_data', nullable=False),
    sa.ForeignKeyConstraint(['user_person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demo_personas',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('person_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('default_module', sa.String(length=50), nullable=False),
    sa.Column('managed_cost_center_id', sa.String(length=50), nullable=True),
    sa.Column('owned_project_ids_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['managed_cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_person_id', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('deep_link_module', sa.String(length=50), nullable=True),
    sa.Column('deep_link_entity_id', sa.String(length=50), nullable=True),
    sa.Column('deep_link_tab', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('review_state', sa.String(length=30), nullable=True),
    sa.Column('submission_feedback', sa.Text(), nullable=True),
    sa.Column('rag_status', sa.String(length=10), nullable=True),
    sa.Column('capex_opex', sa.String(length=10), nullable=False),
    sa.Column('start_month', sa.String(length=7), nullable=False),
    sa.Column('end_month', sa.String(length=7), nullable=True),
    sa.Column('projected_end_month', sa.String(length=7), nullable=True),
    sa.Column('pl_person_id', sa.String(length=50), nullable=True),
    sa.Column('is_service', sa.Boolean(), nullable=False),
    sa.Column('annual_budget', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_budget', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('project_type', sa.Integer(), nullable=True),
    sa.Column('transformation_level', sa.String(length=3), nullable=True),
    sa.Column('tn_standardization', sa.Integer(), nullable=True),
    sa.Column('tn_usage', sa.Integer(), nullable=True),
    sa.Column('tn_maintenance', sa.Integer(), nullable=True),
    sa.Column('tn_financial_benefit', sa.Integer(), nullable=True),
    sa.Column('tn_payback', sa.Integer(), nullable=True),
    sa.Column('tn_competitive_advantage', sa.Integer(), nullable=True),
    sa.Column('tn_value_reserved_1', sa.Integer(), nullable=True),
    sa.Column('tn_value_reserved_2', sa.Integer(), nullable=True),
    sa.Column('complexity_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('value_creation_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('composite_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('tshirt_size', sa.String(length=2), nullable=True),
    sa.Column('pipeline_stage', sa.String(length=30), server_default='Proposed', nullable=False),
    sa.Column('doi', sa.Integer(), nullable=True),
    sa.Column('frozen_doi', sa.Integer(), nullable=True),
    sa.Column('ai_council_approved', sa.Boolean(), nullable=False),
    sa.Column('ai_council_doc_url', sa.Text(), nullable=True),
    sa.Column('within_cutoff', sa.Boolean(), nullable=True),
    sa.Column('run_entity_id', sa.String(length=50), nullable=True),
    sa.Column('handover_month', sa.String(length=7), nullable=True),
    sa.Column('current_milestone_id', sa.Integer(), nullable=True),
    sa.Column('progress_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('progress_pct_manual_override', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('status_narrative', sa.Text(), nullable=True),
    sa.Column('next_milestone_confidence', sa.String(length=20), nullable=True),
    sa.Column('confidence_reason', sa.Text(), nullable=True),
    sa.Column('progress_updated_at', sa.DateTime(), nullable=True),
    sa.Column('progress_updated_by_id', sa.String(length=50), nullable=True),
    sa.Column('last_forecast_submitted_month', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_milestone_id'], ['project_milestones.id'], name='fk_project_current_milestone', use_alter=True),
    sa.ForeignKeyConstraint(['pl_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['progress_updated_by_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['run_entity_id'], ['chargeable_entities.id'], name='fk_project_run_entity', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('headline_impact', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('visibility', sa.String(length=20), server_default='private', nullable=False),
    sa.Column('tier3_content_flag', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('last_recalculated_at', sa.DateTime(), nullable=True),
    sa.Column('cc_owner_scope_cc_id', sa.String(length=50), nullable=True),
    sa.Column('anchor_distribution_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anchor_distribution_version_id'], ['distribution_versions.id'], name='fk_scenario_anchor_distribution_version', use_alter=True),
    sa.ForeignKeyConstraint(['author_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['cc_owner_scope_cc_id'], ['cost_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('pending_values_json', sa.Text(), nullable=False),
    sa.Column('activation_date', sa.Date(), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('created_by_person_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by_person_id', sa.String(length=50), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_comments', sa.Text(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('activation_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('um_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('copied_from_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_person_id', sa.String(length=50), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source IN ('manual', 'csv_upload', 'copy', 'seed')", name='ck_um_version_source'),
    sa.CheckConstraint("status IN ('draft', 'active')", name='ck_um_version_status'),
    sa.CheckConstraint('quarter >= 1 AND quarter <= 4', name='ck_um_version_quarter'),
    sa.ForeignKeyConstraint(['copied_from_version_id'], ['um_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('um_versions', schema=None) as batch_op:
        batch_op.create_index('ix_um_versions_yq_status', ['year', 'quarter', 'status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('person_id', sa.String(length=50), nullable=True),
    sa.Column('tier3_flag', sa.Boolean(), nullable=False),
    sa.Column('change_reviewer_flag', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('actuals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('sub_category', sa.String(length=50), nullable=False),
    sa.Column('hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('capex_opex', sa.String(length=10), nullable=True),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('ext_status', sa.String(length=30), nullable=True),
    sa.Column('po_number', sa.String(length=50), nullable=True),
    sa.Column('invoiced_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=True),
    sa.Column('role_type_id', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['role_type_id'], ['role_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baselines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('sub_category', sa.String(length=50), nullable=False),
    sa.Column('hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('capex_opex', sa.String(length=10), nullable=True),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('ext_status', sa.String(length=30), nullable=True),
    sa.Column('role_type_id', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['role_type_id'], ['role_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('submitted_by_id', sa.String(length=50), nullable=False),
    sa.Column('submission_timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('change_category', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('is_system_suggested', sa.Boolean(), nullable=False),
    sa.Column('source_scenario_id', sa.Integer(), nullable=True),
    sa.Column('cc_owner_id', sa.String(length=50), nullable=True),
    sa.Column('cc_confirmation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('cc_status', sa.String(length=20), nullable=True),
    sa.Column('cc_comments', sa.Text(), nullable=True),
    sa.Column('controller_id', sa.String(length=50), nullable=True),
    sa.Column('controller_approval_timestamp', sa.DateTime(), nullable=True),
    sa.Column('controller_status', sa.String(length=20), nullable=True),
    sa.Column('controller_comments', sa.Text(), nullable=True),
    sa.Column('controller_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cc_owner_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['controller_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chargeable_entities',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('identifier', sa.String(length=40), nullable=False),
    sa.Column('s_code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hierarchy_node_id', sa.String(length=50), nullable=True),
    sa.Column('responsible_person_id', sa.String(length=50), nullable=True),
    sa.Column('allocation_key', sa.String(length=200), nullable=True),
    sa.Column('to_business_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('termination_month', sa.String(length=7), nullable=True),
    sa.Column('annual_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("entity_type IN ('Project', 'Offering', 'InternalService')", name='ck_chargeable_entity_type'),
    sa.ForeignKeyConstraint(['hierarchy_node_id'], ['grouping_entities.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['responsible_person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier', name='uq_chargeable_entity_identifier'),
    sa.UniqueConstraint('project_id', name='uq_chargeable_entity_project')
    )
    with op.batch_alter_table('chargeable_entities', schema=None) as batch_op:
        batch_op.create_index('ix_chargeable_entities_entity_type', ['entity_type'], unique=False)
        batch_op.create_index('ix_chargeable_entities_hierarchy_node', ['hierarchy_node_id'], unique=False)

    op.create_table('distribution_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('active_from', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='draft', nullable=False),
    sa.Column('rationale', sa.Text(), server_default='', nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('copied_from_version_id', sa.Integer(), nullable=True),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_person_id', sa.String(length=50), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("origin IN ('blank', 'copy_active', 'copy_prior', 'seed')", name='ck_distribution_version_origin'),
    sa.CheckConstraint("status IN ('draft', 'active')", name='ck_distribution_version_status'),
    sa.ForeignKeyConstraint(['copied_from_version_id'], ['distribution_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('distribution_versions', schema=None) as batch_op:
        batch_op.create_index('ix_distribution_versions_copied_from', ['copied_from_version_id'], unique=False)
        batch_op.create_index('ix_distribution_versions_scenario', ['scenario_id'], unique=False)
        batch_op.create_index('ix_distribution_versions_status_active_from', ['status', 'active_from'], unique=False)

    op.create_table('external_cost_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('vendor', sa.String(length=200), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=True),
    sa.Column('sub_category', sa.String(length=50), nullable=True),
    sa.Column('milestone_name', sa.String(length=100), nullable=False),
    sa.Column('expected_month', sa.String(length=7), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('delivered_month', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sub_category'], ['external_cost_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_cost_invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('vendor', sa.String(length=200), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('snapshot_month', sa.String(length=7), nullable=False),
    sa.Column('forecast_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('sub_category', sa.String(length=50), nullable=False),
    sa.Column('hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('capex_opex', sa.String(length=10), nullable=True),
    sa.Column('ext_status', sa.String(length=30), nullable=True),
    sa.Column('po_number', sa.String(length=50), nullable=True),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('po_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=True),
    sa.Column('accrual_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=True),
    sa.Column('contract_end_month', sa.String(length=7), nullable=True),
    sa.Column('role_type_id', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.String(length=50), nullable=True),
    sa.Column('is_provisional', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['role_type_id'], ['role_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('predecessor_project_id', sa.String(length=50), nullable=False),
    sa.Column('successor_project_id', sa.String(length=50), nullable=False),
    sa.Column('dependency_type', sa.String(length=30), nullable=False),
    sa.Column('lag_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_person_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['created_by_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['predecessor_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['successor_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_grouping_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('grouping_entity_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['grouping_entity_id'], ['grouping_entities.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_milestones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('milestone_type_id', sa.String(length=50), nullable=True),
    sa.Column('baseline_start', sa.String(length=7), nullable=False),
    sa.Column('baseline_end', sa.String(length=7), nullable=False),
    sa.Column('forecast_start', sa.String(length=7), nullable=False),
    sa.Column('forecast_end', sa.String(length=7), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('baseline_locked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['milestone_type_id'], ['milestone_types.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_submission_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('snapshot_type', sa.String(length=30), nullable=False),
    sa.Column('created_by_id', sa.String(length=50), nullable=False),
    sa.Column('forecast_data_json', sa.Text(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('action_order', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('impact_delta_json', sa.Text(), nullable=True),
    sa.Column('group_label', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(), nullable=True),
    sa.Column('promoted_by_id', sa.String(length=50), nullable=True),
    sa.Column('lever_category', sa.String(length=40), nullable=True),
    sa.Column('tier', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['promoted_by_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_apply_to_forecast_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('applied_by_id', sa.String(length=50), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('cycle_id', sa.String(length=40), nullable=True),
    sa.Column('cycle_label', sa.String(length=60), nullable=True),
    sa.Column('diffs_carried_forward', sa.Integer(), server_default='0', nullable=False),
    sa.Column('diffs_skipped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['applied_by_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenario_apply_to_forecast_events', schema=None) as batch_op:
        batch_op.create_index('ix_scenario_atf_applied_by', ['applied_by_id'], unique=False)
        batch_op.create_index('ix_scenario_atf_scenario', ['scenario_id'], unique=False)

    op.create_table('scenario_capacity_impacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('cost_center_id', sa.String(length=50), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('original_utilization_pct', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('adjusted_utilization_pct', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('fte_delta', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_forecast_cell_edits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('line_key', sa.String(length=120), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('field', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'project_id', 'line_key', 'month', 'field', name='uq_scenario_cell_edit')
    )
    with op.batch_alter_table('scenario_forecast_cell_edits', schema=None) as batch_op:
        batch_op.create_index('ix_scenario_cell_edit_scope', ['scenario_id', 'project_id'], unique=False)

    op.create_table('scenario_line_edits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('line_key', sa.String(length=120), nullable=False),
    sa.Column('op', sa.String(length=10), nullable=False),
    sa.Column('line_kind', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('sub_category', sa.String(length=50), nullable=True),
    sa.Column('role_type_id', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.String(length=50), nullable=True),
    sa.Column('cost_type_id', sa.String(length=50), nullable=True),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('capex_opex', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cost_type_id'], ['external_cost_types.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['role_type_id'], ['role_types.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'project_id', 'line_key', name='uq_scenario_line_edit')
    )
    with op.batch_alter_table('scenario_line_edits', schema=None) as batch_op:
        batch_op.create_index('ix_scenario_line_edit_scope', ['scenario_id', 'project_id'], unique=False)

    op.create_table('scenario_mix_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('cost_center_id', sa.String(length=50), nullable=True),
    sa.Column('swap_from_role_id', sa.String(length=50), nullable=True),
    sa.Column('swap_from_location_id', sa.String(length=50), nullable=True),
    sa.Column('swap_to_role_id', sa.String(length=50), nullable=True),
    sa.Column('swap_to_location_id', sa.String(length=50), nullable=True),
    sa.Column('hours_per_month_swap', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('effective_from', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['swap_from_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['swap_from_role_id'], ['role_types.id'], ),
    sa.ForeignKeyConstraint(['swap_to_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['swap_to_role_id'], ['role_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'project_id', 'cost_center_id', 'swap_from_role_id', 'swap_from_location_id', 'swap_to_role_id', 'swap_to_location_id', name='uq_scenario_mix_change')
    )
    with op.batch_alter_table('scenario_mix_changes', schema=None) as batch_op:
        batch_op.create_index('ix_scenario_mix_change_scope', ['scenario_id', 'project_id'], unique=False)

    op.create_table('scenario_plan_edits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=20), nullable=False),
    sa.Column('milestone_id', sa.String(length=50), server_default='', nullable=False),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('entry_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'project_id', 'target', 'milestone_id', name='uq_scenario_plan_edit')
    )
    with op.batch_alter_table('scenario_plan_edits', schema=None) as batch_op:
        batch_op.create_index('ix_scenario_plan_edit_scope', ['scenario_id', 'project_id'], unique=False)

    op.create_table('scenario_promotions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(), nullable=False),
    sa.Column('promoted_by_id', sa.String(length=50), nullable=False),
    sa.Column('routing_summary_json', sa.Text(), nullable=True),
    sa.Column('promoted_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['promoted_by_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenario_promotions', schema=None) as batch_op:
        batch_op.create_index('ix_scenario_promotions_scenario', ['scenario_id'], unique=False)

    op.create_table('scenario_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('original_budget', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('adjusted_budget', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('budget_delta', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('original_rag', sa.String(length=10), nullable=True),
    sa.Column('adjusted_rag', sa.String(length=10), nullable=True),
    sa.Column('original_start', sa.String(length=7), nullable=True),
    sa.Column('adjusted_start', sa.String(length=7), nullable=True),
    sa.Column('original_end', sa.String(length=7), nullable=True),
    sa.Column('adjusted_end', sa.String(length=7), nullable=True),
    sa.Column('is_affected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_suggestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('suggestion_type', sa.String(length=30), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('impact_description', sa.Text(), nullable=True),
    sa.Column('pre_filled_changes_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('s_code', sa.String(length=20), nullable=False),
    sa.Column('charging_location_id', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.CheckConstraint('value <> 0', name='ck_um_cell_nonzero'),
    sa.ForeignKeyConstraint(['charging_location_id'], ['charging_locations.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['um_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 's_code', 'charging_location_id', name='uq_um_cell_per_version')
    )
    with op.batch_alter_table('user_measurements', schema=None) as batch_op:
        batch_op.create_index('ix_um_cells_version', ['version_id'], unique=False)
        batch_op.create_index('ix_um_cells_version_scode', ['version_id', 's_code'], unique=False)

    op.create_table('allocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('chargeable_entity_id', sa.String(length=50), nullable=True),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chargeable_entity_id'], ['chargeable_entities.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('btc_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('s_code', sa.String(length=20), nullable=True),
    sa.Column('um_snapshot_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('copied_from_profile_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("mode IN ('manual', 'automatic')", name='ck_btc_profile_mode'),
    sa.CheckConstraint("status IN ('draft', 'active')", name='ck_btc_profile_status'),
    sa.ForeignKeyConstraint(['copied_from_profile_id'], ['btc_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['chargeable_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'year', name='uq_btc_profile_entity_year')
    )
    with op.batch_alter_table('btc_profiles', schema=None) as batch_op:
        batch_op.create_index('ix_btc_profiles_entity_year', ['entity_id', 'year'], unique=False)
        batch_op.create_index('ix_btc_profiles_status', ['status'], unique=False)

    op.create_table('capacity_action_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('acting_user_id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('cost_center_id', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail_payload', sa.Text(), nullable=True),
    sa.Column('cr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acting_user_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['cr_id'], ['change_requests.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capacity_action_log', schema=None) as batch_op:
        batch_op.create_index('ix_capacity_action_log_cc', ['cost_center_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_capacity_action_log_project', ['project_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_capacity_action_log_time', ['timestamp'], unique=False)
        batch_op.create_index('ix_capacity_action_log_user', ['acting_user_id', 'timestamp'], unique=False)

    op.create_table('cr_change_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_request_id', sa.Integer(), nullable=False),
    sa.Column('field_changed', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.String(length=200), nullable=True),
    sa.Column('new_value', sa.String(length=200), nullable=True),
    sa.Column('delta', sa.String(length=100), nullable=True),
    sa.Column('line_item_type', sa.String(length=50), nullable=True),
    sa.Column('month', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cr_submission_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_request_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_type', sa.String(length=30), nullable=False),
    sa.Column('created_by_id', sa.String(length=50), nullable=False),
    sa.Column('forecast_data_json', sa.Text(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distributions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('source_entity_id', sa.String(length=50), nullable=False),
    sa.Column('destination_entity_id', sa.String(length=50), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('chain_depth', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('percentage >= 0 AND percentage <= 100', name='ck_distribution_pct_range'),
    sa.CheckConstraint('source_entity_id <> destination_entity_id', name='ck_distribution_no_self_loop'),
    sa.ForeignKeyConstraint(['destination_entity_id'], ['chargeable_entities.id'], ),
    sa.ForeignKeyConstraint(['source_entity_id'], ['chargeable_entities.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['distribution_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'source_entity_id', 'destination_entity_id', name='uq_distribution_edge')
    )
    with op.batch_alter_table('distributions', schema=None) as batch_op:
        batch_op.create_index('ix_distributions_version_dest', ['version_id', 'destination_entity_id'], unique=False)
        batch_op.create_index('ix_distributions_version_source', ['version_id', 'source_entity_id'], unique=False)

    op.create_table('forecast_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('version_type', sa.String(length=20), nullable=False),
    sa.Column('cycle_label', sa.String(length=50), nullable=True),
    sa.Column('cycle_id', sa.String(length=20), nullable=True),
    sa.Column('change_request_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.String(length=50), nullable=False),
    sa.Column('granularity_boundary_months', sa.Integer(), nullable=False),
    sa.Column('planning_horizon_months', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('cell_count', sa.Integer(), nullable=True),
    sa.Column('total_amount_eur', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version_number', name='uq_fv_project_version')
    )
    op.create_table('milestone_deliverables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['completed_by_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['project_milestones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('cycle_label', sa.String(length=50), nullable=True),
    sa.Column('cycle_id', sa.String(length=20), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.String(length=50), nullable=True),
    sa.Column('current_milestone_id', sa.Integer(), nullable=True),
    sa.Column('current_milestone_name', sa.String(length=100), nullable=True),
    sa.Column('current_milestone_sequence', sa.Integer(), nullable=True),
    sa.Column('progress_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('progress_pct_manual_override', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('status_narrative', sa.Text(), nullable=True),
    sa.Column('next_milestone_confidence', sa.String(length=20), nullable=True),
    sa.Column('confidence_reason', sa.Text(), nullable=True),
    sa.Column('checklist_payload_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['current_milestone_id'], ['project_milestones.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_request_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('cost_center_id', sa.String(length=50), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('role_type_id', sa.String(length=50), nullable=True),
    sa.Column('cost_type_id', sa.String(length=50), nullable=True),
    sa.Column('hours_or_amount_per_month', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('period_start', sa.String(length=7), nullable=False),
    sa.Column('period_end', sa.String(length=7), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_person_id', sa.String(length=50), nullable=True),
    sa.Column('adjusted_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('original_hours_per_month', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('change_direction', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['cost_type_id'], ['external_cost_types.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['role_type_id'], ['role_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rollup_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cache_layer', sa.String(length=30), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['distribution_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_layer', 'year', 'version_id', 'key_id', name='uq_rollup_cache_entry')
    )
    with op.batch_alter_table('rollup_cache', schema=None) as batch_op:
        batch_op.create_index('ix_rollup_cache_layer_year_version', ['cache_layer', 'year', 'version_id'], unique=False)

    op.create_table('btc_profile_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('charging_location_id', sa.String(length=50), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.CheckConstraint('percentage > 0 AND percentage <= 100', name='ck_btc_profile_line_pct_range'),
    sa.ForeignKeyConstraint(['charging_location_id'], ['charging_locations.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['btc_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'charging_location_id', name='uq_btc_profile_line_profile_cl')
    )
    with op.batch_alter_table('btc_profile_lines', schema=None) as batch_op:
        batch_op.create_index('ix_btc_profile_lines_profile', ['profile_id'], unique=False)

    op.create_table('resource_request_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_request_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('person_id', sa.String(length=50), nullable=False),
    sa.Column('hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['resource_request_id'], ['resource_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_request_id', 'month', 'person_id', name='uq_rra_request_month_person')
    )
    op.create_table('scenario_project_anchors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('forecast_version_id', sa.Integer(), nullable=False),
    sa.Column('rebased_from_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_version_id'], ['forecast_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['rebased_from_version_id'], ['forecast_versions.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'project_id', name='uq_scenario_project_anchor')
    )
    with op.batch_alter_table('scenario_project_anchors', schema=None) as batch_op:
        batch_op.create_index('ix_scenario_project_anchors_scenario', ['scenario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_project_anchors', schema=None) as batch_op:
        batch_op.drop_index('ix_scenario_project_anchors_scenario')

    op.drop_table('scenario_project_anchors')
    op.drop_table('resource_request_assignments')
    with op.batch_alter_table('btc_profile_lines', schema=None) as batch_op:
        batch_op.drop_index('ix_btc_profile_lines_profile')

    op.drop_table('btc_profile_lines')
    with op.batch_alter_table('rollup_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_rollup_cache_layer_year_version')

    op.drop_table('rollup_cache')
    op.drop_table('resource_requests')
    op.drop_table('progress_snapshots')
    op.drop_table('milestone_deliverables')
    op.drop_table('forecast_versions')
    with op.batch_alter_table('distributions', schema=None) as batch_op:
        batch_op.drop_index('ix_distributions_version_source')
        batch_op.drop_index('ix_distributions_version_dest')

    op.drop_table('distributions')
    op.drop_table('cr_submission_snapshots')
    op.drop_table('cr_change_details')
    with op.batch_alter_table('capacity_action_log', schema=None) as batch_op:
        batch_op.drop_index('ix_capacity_action_log_user')
        batch_op.drop_index('ix_capacity_action_log_time')
        batch_op.drop_index('ix_capacity_action_log_project')
        batch_op.drop_index('ix_capacity_action_log_cc')

    op.drop_table('capacity_action_log')
    with op.batch_alter_table('btc_profiles', schema=None) as batch_op:
        batch_op.drop_index('ix_btc_profiles_status')
        batch_op.drop_index('ix_btc_profiles_entity_year')

    op.drop_table('btc_profiles')
    op.drop_table('allocations')
    with op.batch_alter_table('user_measurements', schema=None) as batch_op:
        batch_op.drop_index('ix_um_cells_version_scode')
        batch_op.drop_index('ix_um_cells_version')

    op.drop_table('user_measurements')
    op.drop_table('system_suggestions')
    op.drop_table('scenario_states')
    with op.batch_alter_table('scenario_promotions', schema=None) as batch_op:
        batch_op.drop_index('ix_scenario_promotions_scenario')

    op.drop_table('scenario_promotions')
    with op.batch_alter_table('scenario_plan_edits', schema=None) as batch_op:
        batch_op.drop_index('ix_scenario_plan_edit_scope')

    op.drop_table('scenario_plan_edits')
    with op.batch_alter_table('scenario_mix_changes', schema=None) as batch_op:
        batch_op.drop_index('ix_scenario_mix_change_scope')

    op.drop_table('scenario_mix_changes')
    with op.batch_alter_table('scenario_line_edits', schema=None) as batch_op:
        batch_op.drop_index('ix_scenario_line_edit_scope')

    op.drop_table('scenario_line_edits')
    with op.batch_alter_table('scenario_forecast_cell_edits', schema=None) as batch_op:
        batch_op.drop_index('ix_scenario_cell_edit_scope')

    op.drop_table('scenario_forecast_cell_edits')
    op.drop_table('scenario_capacity_impacts')
    with op.batch_alter_table('scenario_apply_to_forecast_events', schema=None) as batch_op:
        batch_op.drop_index('ix_scenario_atf_scenario')
        batch_op.drop_index('ix_scenario_atf_applied_by')

    op.drop_table('scenario_apply_to_forecast_events')
    op.drop_table('scenario_actions')
    op.drop_table('project_submission_snapshots')
    op.drop_table('project_milestones')
    op.drop_table('project_grouping_assignments')
    op.drop_table('project_dependencies')
    op.drop_table('forecasts')
    op.drop_table('forecast_snapshots')
    op.drop_table('external_cost_invoices')
    op.drop_table('external_cost_deliveries')
    with op.batch_alter_table('distribution_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_distribution_versions_status_active_from')
        batch_op.drop_index('ix_distribution_versions_scenario')
        batch_op.drop_index('ix_distribution_versions_copied_from')

    op.drop_table('distribution_versions')
    with op.batch_alter_table('chargeable_entities', schema=None) as batch_op:
        batch_op.drop_index('ix_chargeable_entities_hierarchy_node')
        batch_op.drop_index('ix_chargeable_entities_entity_type')

    op.drop_table('chargeable_entities')
    op.drop_table('change_requests')
    op.drop_table('baselines')
    op.drop_table('actuals')
    op.drop_table('users')
    with op.batch_alter_table('um_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_um_versions_yq_status')

    op.drop_table('um_versions')
    op.drop_table('scheduled_changes')
    op.drop_table('scenarios')
    op.drop_table('projects')
    op.drop_table('notifications')
    op.drop_table('demo_personas')
    op.drop_table('audit_log')
    op.drop_table('workflow_step_actions')
    op.drop_table('people')
    op.drop_table('legal_entities')
    op.drop_table('workflow_steps')
    op.drop_table('saved_report_shares')
    op.drop_table('rate_table')
    op.drop_table('grouping_hierarchy_levels')
    op.drop_table('grouping_entities')
    op.drop_table('cost_centers')
    op.drop_table('charging_locations')
    op.drop_table('workflow_templates')
    op.drop_table('saved_views')
    op.drop_table('saved_reports')
    op.drop_table('role_types')
    op.drop_table('role_permission_grants')
    op.drop_table('regions')
    op.drop_table('planning_parameters')
    op.drop_table('milestone_types')
    op.drop_table('locations')
    op.drop_table('kpi_definitions')
    op.drop_table('grouping_hierarchies')
    op.drop_table('grouping_entity_types')
    op.drop_table('external_cost_types')
    op.drop_table('countries')
    op.drop_table('competence_centers')
    # ### end Alembic commands ###
