#!/usr/bin/env python3
"""
Seed data generator runner.
Calls each module in dependency order and writes seed.sql.
"""
import importlib
import os
import sys

# Modules to run in order
MODULES = [
    "s01_organization",
    "s02_roles_rates",
    "s03_people",
    "s04_programs_projects",
    "s05_financials",
    "s06_allocations",
    "s07_change_requests",
    "s08_workflow",
    "s09_phases",
    "s10_scenarios",
]


def main():
    parts = []
    parts.append("-- =============================================================================")
    parts.append("-- CRETA Demo App — Seed Data (v3)")
    parts.append("-- Generated by backend/seed/generate_seed/runner.py")
    parts.append("-- Demo date: April 2026")
    parts.append("-- =============================================================================")
    parts.append("")

    for mod_name in MODULES:
        print(f"  Generating {mod_name}...", file=sys.stderr)
        mod = importlib.import_module(f"generate_seed.{mod_name}")
        sql = mod.generate()
        parts.append(sql)
        parts.append("")

    output = "\n".join(parts)

    # Write to seed.sql
    seed_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "seed.sql")
    with open(seed_path, "w") as f:
        f.write(output)

    # Count lines
    line_count = output.count("\n") + 1
    print(f"\n  Done! Wrote {line_count} lines to {seed_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
